services:
  db:
      image: postgres:15
      networks:
        - sonarnet
      environment:
        - POSTGRES_USER=sonar
        - POSTGRES_PASSWORD=sonar
        - POSTGRES_DB=sonarqube
      volumes:
        - postgresql_data:/var/lib/postgresql/data
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube_local
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    networks:
      - sonarnet
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs 
  azureagent:
    build:
      context: .
      dockerfile: DockerFile
    image: croissant-agent:latest
    container_name: croissant_local_ppol
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    networks:
      - sonarnet

  croissant-web-prod:
    image: nginx:alpine
    container_name: croissant_prod_app
    ports:
      - "8080:80"
    networks:
      - sonarnet
    volumes:
      - web_data:/usr/share/nginx/html
networks:
  sonarnet:

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql_data:
  web_data: